name: packer
"on":
  push:
    branches:
      - "**"
jobs:
  first-attempt:
    uses: ./.github/workflows/packer-job.yml
  second-attempt:
    needs: first-attempt
    if: failure()
    uses: ./.github/workflows/packer-job.yml
  third-attempt:
    needs: first-attempt
    if: failure()
    uses: ./.github/workflows/packer-job.yml
  required-check:
    needs:
      - first-attempt
      - second-attempt
      - third-attempt
    if: |
      always() &&
      (needs.first-attempt.result == 'success' || needs.second-attempt.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - run: echo "All tests passed!"
