name: packer
"on":
  push:
    branches:
      - "**"
jobs:
  attempt-1:
    uses: ./.github/workflows/packer-job.yml
  attempt-2:
    needs: attempt-1
    if: needs.attempt-1.outputs.success != 'true'
    uses: ./.github/workflows/packer-job.yml
  attempt-3:
    needs: attempt-2
    if: needs.attempt-2.outputs.success != 'true'
    uses: ./.github/workflows/packer-job.yml
  required-check:
    needs:
      - attempt-1
      - attempt-2
      - attempt-3
    if: always()
    runs-on: ubuntu-latest
    steps:
      - if: needs.attempt-1.result == 'success' || needs.attempt-2.result == 'success'
        run: echo "Build succeeded!"
      - if: needs.attempt-1.result != 'success' && needs.attempt-2.result != 'success'
        run: |
          echo "All attempts failed"
          exit 1
